---
title: "Exploratory data analysis"
output:
  html_document:
    df_print: paged
---

```{r}
library(plyr)
library(tidyverse)
library(data.table)
library(plotly)
library(reshape2)
library(eurostat)
require(gridExtra)
library(lubridate)
```

```{r}
coronanet <- read_csv("https://raw.githubusercontent.com/LuMesserschmidt/WEP_analysis/master/data/CoronaNet/coronanet_internal.csv") %>%
  filter(country %in% c("France", "Germany", "Italy", "Switzerland"))
```

```{r}
italy <- read_csv("data/Cases/Italy/italy_dashboard/data_regions.csv")
france <- read_csv("data/Cases/France/france_subnational.csv")
germany <- read_csv("data/Cases/Germany/cases-rki-by-state.csv")
```

```{r}
dir <- "data/switzerland_openzh/"
files <- list.files(path = dir, pattern = "*.csv", full.names = TRUE)
switzerland <- files %>%
  map(read_csv) %>%
  rbind.fill()
```

```{r}
name <- c("date", "Schleswig-Holstein", "Hamburg", "Lower Saxony", "Bremen",
          "North Rhine-Westphalia", "Hesse", "Rheinland-Pfalz", "Baden-Wuerttemberg",
          "Bavaria", "Saarland", "Brandenburg", "Mecklenburg-Vorpommern",
          "Saxony", "Saxony-Anhalt", "Thuringia", "Berlin", "sum_cases")
setnames(germany, name)
```


```{r}
germany <- germany %>%
  melt(id.vars=c("date")) %>%
  setnames(c("date", "province", "sum_cases"))
```

```{r}
france$other_hospitalization <- france$hospitalises - france$reanimation
```

```{r}
france <- france %>%
  select(date, nom, casConfirmes, deces, reanimation, other_hospitalization, gueris)
```

```{r}
colsum <- france$deces + france$reanimation + france$other_hospitalization + france$gueris
```

```{r}
france$estimated_cases <- sapply(1:nrow(france), function (i) { if (!is.na(france$casConfirmes[[i]])) {france$casConfirmes[i]} else {colsum[[i]]}})
```

```{r}
france <- france %>%
  select(date, nom, estimated_cases)
```

```{r}
italy <- italy %>%
  select(data, denominazione_regione, totale_casi) %>%
  setnames(c("date", "region", "cases"))
```

```{r}
switzerland <- switzerland %>%
  select(date, abbreviation_canton_and_fl, ncumul_conf) %>%
  setnames(c("date", "region", "cases"))
```

```{r}
write_csv(cases_combined, "C:/Users/Anelia/Desktop/projects/coronanet/WEP/WEP_analysis/data/combined_cases7.csv")
```

```{r}
suedtirol <- cases_combined %>%
  filter(country == "Italy") %>%
  filter(region == "P.A. Bolzano" | region == "P.A. Trento")
```

```{r}
suedtirol <- unique(suedtirol)
```


```{r}
suedtirol <- aggregate(list(cases=suedtirol$cases), by=list(date=suedtirol$date), FUN=sum)
```

```{r}
suedtirol$region <- "Trentino-Alto Adige"
suedtirol$country <- "Italy"
```

```{r}
suedtirol <- setnames(suedtirol, c("data", "cases", "region", "country"))
```

```{r}
suedtirol <- suedtirol %>%
  select(date, region, cases, country)
```

```{r}
cases_combined <- rbind(unique(cases_combined), suedtirol) %>%
  filter(region != "P.A. Bolzano") %>%
  filter(region != "P.A. Trento") %>%
  arrange(country, region, date)
```

```{r}
cases_germany <- cases_combined %>% filter(country == "Germany")
cases_france <- cases_combined %>% filter(country == "France")
cases_italy <- cases_combined %>% filter(country == "Italy")
cases_switzerland <- cases_combined %>% filter(country == "Switzerland")
```

```{r}
#federal_germany <- cases_combined %>% filter(country == "Germany") %>% filter(region == "Federal")
federal_germany
```

```{r}
coronanet_germany %>% select(date_announced, confirmed_cases) %>% unique() %>% arrange(date_announced)
```

```{r}
#liechtenstein <- cases_combined %>% filter(country == "Switzerland" & region == "Federal")
#liechtenstein$region <- "Principality of Liechtenstein"
#cases_combined <- rbind(cases_combined, liechtenstein)
cases_combined <- cases_combined %>% filter(region != "Federal")
```

```{r}
cases_combined <- read_csv("C:/Users/Anelia/Desktop/projects/coronanet/WEP/WEP_analysis/data/combined_cases5.csv")
eurostat <- read_csv("C:/Users/Anelia/Desktop/projects/coronanet/WEP/WEP_analysis/data/eurostat_data_v2.csv")
```

```{r}
View(search_eurostat("NUTS 3", type = "all"))
```

```{r}
#reg <- function(x) { grepl("^DE[1-9A-G]$", x) | grepl("^CH0[1-7]$", x) | grepl("^FR[1-9A-M]$|^FRY[1-5]$", x) | grepl("^IT[A-Z][1-9]$", x)}
reg <- function(x) { grepl("^DE$", x) | grepl("^CH$", x) | grepl("^FR$", x) | grepl("^IT$", x)}
activity_rates <- get_eurostat("lfst_r_lfp2actrtn", time_format = "num") %>%
  filter(reg(geo)) %>%
  filter(time == max(time)) %>%
  left_join(geodict, by=c("geo" = "code")) %>%
  filter(citizen == "EU27_2020_FOR" & isced11 == "TOTAL" & age == "Y15-64" & sex == "T") %>%
  select(values, region) %>%
  setnames(c("eurostat_activity_rate_2019", "region"))
agriculture <- get_eurostat("agr_r_accts", time_format = "num") %>%
  filter(reg(geo)) %>%
  filter(time == max(time)) %>%
  filter(unit == "MIO_EUR") %>%
  filter(indic_ag == "PROD_BP") %>%
  left_join(geodict, by=c("geo" = "code")) %>%
  inner_join(agrdict, by = c("itm_newa" = "Notation")) %>%
  filter(itm_newa %in% c("01000", "04000", "12000", "13000", "16000")) %>%
  dcast(geo + region ~ indic_ag + Label + unit, fun.aggregate = median, value.var = "values") %>%
  select(-geo) %>%
  setnames(c("region", "eurostat_prodbp_agricultural_output_mioeur_2018", 
             "eurostat_prodbp_animal_output_mioeur_2018", "eurostat_prodbp_animal_products_mioeur_2018", "eurostat_prodbp_cereals_seeds_mioeur_2018", "eurostat_prodbp_vegetables_horticultural_mioeur_2018"))
poverty_risk <- get_eurostat("ilc_li41", time_format = "num") %>%
  filter(reg(geo)) %>%
  filter(time == max(time)) %>%
  left_join(geodict, by=c("geo" = "code")) %>%
  select(region, values) %>%
  setnames(c("region", "eurostat_poverty_risk_rate_2018"))
employment_education <- get_eurostat("lfst_r_lfe2eedu", time_format = "num") %>%
  filter(reg(geo)) %>%
  filter(time == max(time)) %>%
  left_join(geodict, by=c("geo" = "code")) %>%
  filter(sex == "T" & isced11 == "TOTAL" & age == "Y_GE15") %>%
  select(region, values) %>%
  setnames(c("region", "eurostat_employment_thousands_2019"))
employment_sector_growth_2017 <- get_eurostat("sbs_r_nuts06_r2", time_format = "num") %>%
  filter(reg(geo)) %>%
  filter(time == max(time)) %>%
  left_join(geodict, by=c("geo" = "code")) %>%
  filter(indic_sb %in% c("V11210", "V13320", "V16110", "V91290", "V94310")) %>%
  filter(nace_r2 %in% c("A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "L",
                        "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V",
                        "W", "X", "Y", "Z")) %>%
  inner_join(nacer2dict, by=c("nace_r2" = "Notation")) %>%
  inner_join(indicsbdict, by=c("indic_sb" = "Notation")) %>%
  dcast(geo + region ~ Label.x + Label.y, fun.aggregate = median, value.var = "values") %>%
  select(-geo)
employment_sector_activity <- get_eurostat("nama_10r_2emhrw", time_format = "num") %>%
  filter(reg(geo)) %>%
  filter(time == max(time)) %>%
  left_join(geodict, by=c("geo" = "code")) %>%
  left_join(nacer2dict, by=c("nace_r2" = "Notation")) %>%
  dcast(geo + region ~ Label, fun.aggregate = median, value.var = "values") %>%
  select(-geo)
gdp <- get_eurostat("nama_10r_2gdp", time_format = "num") %>%
  filter(reg(geo)) %>%
  filter(time == max(time)) %>%
  filter(unit %in% c("MIO_EUR", "EUR_HAB")) %>%
  left_join(geodict, by=c("geo" = "code")) %>%
  dcast(geo + region ~ unit, fun.aggregate = median, value.var = "values") %>%
  select(region, MIO_EUR, EUR_HAB) %>%
  setnames(c("region", "eurostat_gdp_mio_eur_2018", "eurostat_gdp_eur_hab_2018"))
health_personnel <- get_eurostat("hlth_rs_prsrg", time_format = "num") %>%
  filter(reg(geo)) %>%
  # not enough info otherwise
  filter(time == "2018") %>%
  left_join(geodict, by=c("geo" = "code")) %>%
  dcast(geo + region ~ unit, fun.aggregate = median, value.var = "values") %>%
  select(region, HAB_P, NR, P_HTHAB) %>%
  setnames(c("region", "eurostat_inhabitants_per_doctor_2018", "eurostat_doctors_nr_2018", "eurostat_doctors_per_100000_inhabitants_2018"))
hospital_beds <- get_eurostat("hlth_rs_bdsrg", time_format = "num") %>%
  filter(reg(geo)) %>%
  filter(time == max(time)) %>%
  left_join(geodict, by=c("geo" = "code")) %>%
  dcast(geo + region ~ unit, fun.aggregate = median, value.var = "values") %>%
  select(region, HAB_P, NR, P_HTHAB) %>%
  setnames(c("region", "eurostat_inhabitants_per_hospital_beds_2018", "eurostat_hospital_beds_nr_2018", "eurostat_hospital_beds_per_100000_inhabitants_2018"))
household_income <- get_eurostat("nama_10r_2hhinc", time_format = "num") %>%
  filter(reg(geo)) %>%
  filter(time == "2017") %>%
  filter(unit %in% c("MIO_EUR", "EUR_HAB")) %>%
  filter(na_item %in% c("B5N", "B7N")) %>%
  left_join(geodict, by=c("geo" = "code")) %>%
  dcast(geo + region ~ unit, fun.aggregate = median, value.var = "values") %>%
  select(region, MIO_EUR, EUR_HAB) %>%
  setnames(c("region", "eurostat_household_income_mioeur_B5N_2017", "eurostat_household_income_eur_per_inhabitant_B5N_2017"))
long_term_unemployment <- get_eurostat("lfst_r_lfu2ltu", time_format = "num") %>%
  filter(reg(geo)) %>%
  filter(time == max(time)) %>%
  left_join(geodict, by=c("geo" = "code")) %>%
  dcast(geo + region ~ unit, fun.aggregate = median, value.var = "values") %>%
  select(region, PC_ACT, PC_UNE, THS) %>%
  setnames(c("region", "eurostat_lt_unemp_percentage_active_2019", "eurostat_lt_unemp_percentage_unemp_2019", "eurostat_lt_unemp_thousands_2019"))
percentage_unemployment_gender <- get_eurostat("lfst_r_lfu3rt", time_format = "num") %>%
  filter(reg(geo)) %>%
  filter(time == max(time)) %>%
  left_join(geodict, by=c("geo" = "code")) %>%
  filter(age == "Y_GE15") %>%
  select(region, values) %>%
  setnames(c("region", "eurostat_percentage_unemployment_2019"))
population_education <- get_eurostat("edat_lfse_04", time_format = "num") %>%
  filter(reg(geo)) %>%
  filter(time == max(time)) %>%
  filter(sex == "T") %>%
  left_join(geodict, by=c("geo" = "code")) %>%
  dcast(geo + region ~ isced11, fun.aggregate = median, value.var = "values") %>%
  select(region, "ED0-2", "ED3-8", "ED3_4", "ED5-8") %>%
  setnames(c("region", "eurostat_percentage_ED0-2_2019", "eurostat_percentage_ED3-8_2019", "eurostat_percentage_ED3_4_2019",
             "eurostat_percentage_ED5-8_2019"))
population_sex <- get_eurostat("demo_r_d2jan", time_format = "num") %>%
  filter(reg(geo)) %>%
  filter(time == max(time)) %>%
  filter(age == "TOTAL") %>%
  left_join(geodict, by=c("geo" = "code")) %>%
  dcast(geo + region ~ sex, fun.aggregate = median, value.var = "values") %>%
  select(region, "F", "M", "T") %>%
  setnames(c("region", "eurostat_female_population_2019", "eurostat_male_population_2019", "eurostat_total_population_2019"))
poverty_exclusion <- get_eurostat("ilc_peps11", time_format = "num") %>%
  filter(reg(geo)) %>%
  filter(time == max(time)) %>%
  left_join(geodict, by=c("geo" = "code")) %>%
  select(region, values) %>%
  setnames(c("region", "eurostat_risk_poverty_or_social_exclusion_2019"))
severe_deprivation <- get_eurostat("ilc_mddd21", time_format = "num") %>%
  filter(reg(geo)) %>%
  filter(time == max(time)) %>%
  left_join(geodict, by=c("geo" = "code")) %>%
  select(region, values) %>%
  setnames(c("region", "eurostat_severe_material_deprivation_rate_2018"))
unemployment_sex <- get_eurostat("lfst_r_lfu3pers", time_format = "num") %>%
  filter(reg(geo)) %>%
  filter(time == max(time)) %>%
  left_join(geodict, by=c("geo" = "code")) %>%
  filter(age == "Y_GE15") %>%
  dcast(geo + region ~ sex, fun.aggregate = median, value.var = "values") %>%
  select(region, "F", "M", "T") %>%
  setnames(c("region", "eurostat_female_unemployment_thousand_2019", "eurostat_male_unemployment_thousand_2019", "eurostat_total_unemployment_thousand_2019"))
```

```{r}
get_eurostat("demo_r_d3dens", time_format = "num") %>%
  filter(grepl("CH0[0-9][0-9]", geo))
```

```{r}
eurostat_data <- activity_rates %>%
  left_join(agriculture, by="region") %>%
  left_join(poverty_risk, by="region") %>%
  left_join(employment_education, by="region") %>%
  left_join(employment_sector_growth_2017, by="region") %>%
  left_join(employment_sector_activity, by="region") %>%
  left_join(gdp, by="region") %>%
  left_join(health_personnel, by="region") %>%
  left_join(hospital_beds, by="region") %>%
  left_join(household_income, by="region") %>%
  left_join(long_term_unemployment, by="region") %>%
  left_join(percentage_unemployment_gender, by="region") %>%
  left_join(population_education, by="region") %>%
  left_join(population_sex, by="region") %>%
  left_join(poverty_exclusion, by="region") %>%
  left_join(severe_deprivation, by="region") %>%
  left_join(unemployment_sex, by="region")
```

```{r}
write_csv(eurostat_data, "C:/Users/Anelia/Desktop/projects/coronanet/WEP/WEP_analysis/data/eurostat_data_national.csv")
```


```{r}
activity_rates %>%
  dcast(geo + region ~ isced11 + age + sex, fun.aggregate = median, value.var = "values")
agriculture %>%
  select(-unit) %>%
  dcast(geo + region ~ indic_ag + itm_newa, fun.aggregate = median, value.var = "values")
poverty_risk %>%
  select(-unit)
employment_education %>%
  select(-unit) %>%
  dcast(geo + region ~ isced11 + age + sex, fun.aggregate = median, value.var = "values")
employment_sector_growth %>%
  dcast(geo + region ~ nace_r2 + indic_sb, fun.aggregate = median, value.var = "values")
employment_sector_activity %>%
  #mutate(values = values * 1000) %>%
  select(-unit) %>%
  dcast(geo + region ~ wstatus + nace_r2, fun.aggregate = median, value.var = "values")
gdp %>%
  dcast(geo + region ~ unit, fun.aggregate = median, value.var = "values")
health_personnel %>%
  dcast(geo + region ~ isco08, fun.aggregate = median, value.var = "values")
hospital_beds %>%
  dcast(geo + region ~ unit, fun.aggregate = median, value.var = "values")
household_income %>%
  dcast(geo + region ~ unit + direct + na_item, fun.aggregate = median, value.var = "values")
long_term_unemployment %>%
  dcast(geo + region ~ unit, fun.aggregate = median, value.var = "values")
percentage_unemployment_gender %>%
  dcast(geo + region ~ age + sex, fun.aggregate = median, value.var = "values")
population_education %>%
  dcast(geo + region ~ age + sex, fun.aggregate = median, value.var = "values")
population_gender %>%
  dcast(geo + region ~ age + sex, fun.aggregate = median, value.var = "values")
poverty_exclusion %>%
  select(-unit)
severe_deprivation %>%
  select(-unit)
unemployment_gender %>%
  select(-unit) %>%
  dcast(geo + region ~ age + sex, fun.aggregate = median, value.var = "values")
```


```{r}
#activity_rates <- activity_rates %>%
#  select(-citizen, -unit, -time)
activity_rates2 <- activity_rates %>%
  #reshape(idvar = c("geo", "region"), timevar = "isced11", direction = "wide")
  melt(id=c("geo", "region", "values")) %>%
  dcast(geo + region + values ~ value)
  #dcast(geo + region ~ isced11 + age + sex)
education <- activity_rates2 %>%
  select(geo, region, values, `ED0-2`, ED3_4, `ED5-8`, NRP, TOTAL) %>%
  group_by(geo, region, values) %>%
  #mutate_each(funs(an = as.numeric(as.character(.)))) %>%
  gather(education, val, -geo, -region, -values) %>%
  filter(val == 1) %>%
  select(-val) %>%
  arrange(geo, region, values)
age <- activity_rates2 %>%
  select(geo, region, values, `Y15-64`, `Y20-64`, `Y25-54`, `Y55-64`) %>%
  group_by(geo, region, values) %>%
  gather(age, val, -geo, -region, -values) %>%
  filter(val == 1) %>%
  select(-val) %>%
  arrange(geo, region, values)
sex <- activity_rates2 %>%
  select(geo, region, values, `F`, `M`, `T`) %>%
  group_by(geo, region, values) %>%
  gather(sex, val, -geo, -region, -values) %>%
  filter(val == 1) %>%
  select(-val) %>%
  arrange(geo, region, values)
```

```{r}
education %>%
  inner_join(sex, by=c("geo" = "geo", "region" = "region", "values" = "values")) %>%
  inner_join(age, by=c("geo" = "geo", "region" = "region", "values" = "values"))
```

```{r}
geodict <- read_delim("C:/Users/Anelia/Desktop/projects/coronanet/WEP/WEP_analysis/data/geo.dic", "\t", col_names = c("code", "region"))
agrdict <- read_csv("C:/Users/Anelia/Desktop/projects/coronanet/WEP/WEP_analysis/data/itm_newa.csv") %>%
  select(Label, Notation)
nacer2dict <- read_csv("C:/Users/Anelia/Desktop/projects/coronanet/WEP/WEP_analysis/data/nace_r2.csv") %>%
  select(Label, Notation)
indicsbdict <- read_csv("C:/Users/Anelia/Desktop/projects/coronanet/WEP/WEP_analysis/data/indic_sb.csv") %>%
  select(Label, Notation)
```


```{r, out.width="100%"}
fig1 <- plot_ly(cases_germany, x=~date, y=~cases, name=~region, type = 'scatter', mode = 'lines')
fig2 <- plot_ly(cases_france, x=~date, y=~cases, name=~region, type = 'scatter', mode = 'lines')
fig3 <- plot_ly(cases_italy, x=~date, y=~cases, name=~region, type = 'scatter', mode = 'lines')
fig4 <- plot_ly(cases_switzerland, x=~date, y=~cases, name=~region, type = 'scatter', mode = 'lines')
# sharing y axis flattens Switzerland data
fig <- subplot(fig1, fig2, fig3, fig4, nrows = 2, shareY = FALSE) %>%
  layout(showlegend = FALSE,
         title = "Cumulative COVID-19 cases per region")
fig
```

```{r}
p1 <- ggplot(cases_germany, aes(x=date, y=cases, group=region)) + geom_line()
p2 <- ggplot(cases_france, aes(x=date, y=cases, group=region)) + geom_line()
p3 <- ggplot(cases_italy, aes(x=date, y=cases, group=region)) + geom_line()
p4 <- ggplot(cases_switzerland, aes(x=date, y=cases, group=region)) + geom_line()
grid.arrange(p1, p2, p3, p4, nrow = 2)
```


```{r}
coronanet_germany <- coronanet %>%
  filter(country == "Germany")
```

```{r}
coronanet_germany %>%
  left_join(germany, by = c("province" = "display_name", "date_start" = "date"))
```

```{r}
plot_ly(cases_italy %>% filter(region == "Aosta Valley"), x=~date, y=~cases)
```

```{r}
merged <- read_csv("C:/Users/Anelia/Desktop/projects/coronanet/WEP/WEP_analysis/data/merged_v2.csv")
```

```{r}
eurostat  <- eurostat %>%
  filter(!code %in% c("CH040", "CH070", "DE30", "DE300", "DE_CAP", "DE40",
                      "DE50", "DE60", "DE600", "DE60000001", "DE80", "DEC0",
                      "DEE0", "DEF0", "DEG0", "FR10", "FRB0", "FRG0", "FRH0",
                      "FRL0", "FRM0", "FRY10", "FRY20", "FRY30", "FRY40", "FRY50",
                      "ITC20"))
```

```{r}
eurostat$region <- gsub("Provincia Autonoma di Trento", "Trentino-Alto Adige", eurostat$region)
```


```{r}
eurostat %>%
  group_by(region) %>%
  tally()
```

```{r}
cases_combined %>%
  group_by(region) %>%
  tally()
```

```{r}
cases_combined %>%
  right_join(coronanet %>% filter(init_country_level != "National"), by=c("country" = "country", "region" = "province", "date" = "date_announced")) %>%
  left_join(eurostat, by=c("region" = "region")) #%>%
  #write_csv("C:/Users/Anelia/Desktop/projects/coronanet/WEP/WEP_analysis/data/merged_v1.csv")
```

```{r}
swiss <- get_eurostat("demo_r_pjangrp3", time_format = "num") %>%
  filter(grepl("CH[0-9][0-9][0-9]", geo)) %>%
  filter(age == "TOTAL" & sex == "T" & time == "2019") %>%
  select(geo, eurostat_population_2019 = values) %>%
  left_join(geodict, by=c("geo" = "code"))
```

```{r}
swiss$region <- gsub("St. Gallen", "Saint Gallen", swiss$region)
```


```{r}
swiss %>%
  arrange(region)
```


```{r}
cases_combined %>%
  filter(country == "Switzerland") %>%
  group_by(region) %>%
  tally()
```

```{r}
coronanet_national <- coronanet %>%
  filter(init_country_level == "National")
coronanet_regional <- coronanet %>%
  filter(init_country_level != "National")
```

```{r}
eurostat_d <- read_csv("C:/Users/Anelia/Desktop/projects/coronanet/WEP/WEP_analysis/data/eurostat_data_national.csv")
```


```{r}
merged_national <- cases_combined %>%
  filter(region == "National") %>%
  full_join(coronanet_national, by=c("country" = "country", "date" = "date_announced")) %>%
  left_join(eurostat_d, by=c("region" = "region")) #%>%
  #left_join(swiss, by = c("region" = "region"))
```


```{r}
merged_regional <- cases_combined %>%
  filter(region != "National") %>%
  full_join(coronanet_regional, by=c("country" = "country", "region" = "province", "date" = "date_announced")) %>%
  left_join(eurostat, by=c("region" = "region")) %>%
  left_join(swiss, by = c("region" = "region"))
```

```{r}
write_csv(merged_national, "C:/Users/Anelia/Desktop/projects/coronanet/WEP/WEP_analysis/data/merged_national.csv")
write_csv(merged_regional, "C:/Users/Anelia/Desktop/projects/coronanet/WEP/WEP_analysis/data/merged_regional.csv")
```

```{r}
merged_regional <- merged_regional %>%
  select(-eurostat_population_2019)
```

```{r}
merged_national <- merged_national %>%
  select(-`Water supply; sewerage, waste management and remediation activities_Share of employment in manufacturing total - percentage`)
```


```{r}
setdiff(names(merged_regional), names(merged_national))
```


```{r}
merged_regional$eurostat_total_population_2019 <- sapply(1:nrow(merged_regional), function (i) { if (!is.na(merged_regional$eurostat_total_population_2019[[i]])) {merged_regional$eurostat_total_population_2019[[i]]} else {merged_regional$eurostat_population_2019[[i]]}})
```

```{r}
merged$NUTS_code <- sapply(1:nrow(merged), function (i) { if (!is.na(merged$code[[i]])) {merged$code[[i]]} else {merged$geo[[i]]}})
```

```{r}
merged <- merged %>%
  select(-geo, -code, -eurostat_population_2019, -eurostat_total_population_2019)
```

```{r}
write_csv(merged, "C:/Users/Anelia/Desktop/projects/coronanet/WEP/WEP_analysis/data/merged_v5.csv")
```


```{r}
merged %>%
  group_by(date, region) %>%
  tally()
```

```{r}
days <- seq(from=as.Date('2020-01-01'), to=as.Date("2020-07-28"),by='days')
for (i in seq_along(days)) {
  for (x in unique(cases_combined$region)) {
    if (length(cases_combined[cases_combined$region == x & cases_combined$date == days[i],]$country) < 1) {
      cases_combined <- rbind(cases_combined, data.frame(date = days[i], region = x, cases = 0, country = cases_combined[cases_combined$region == x,]$country[1]))
    }
  }
}

```

```{r}
length(cases_combined[cases_combined$region == "Bavaria" & cases_combined$date == "2020-03-31",]$country)
```

```{r}
cases_combined <- cases_combined %>%
  arrange(date, country, region)
```

```{r}
merged <- read_csv("C:/Users/Anelia/Desktop/projects/coronanet/WEP/WEP_analysis/data/merged_v5.csv")
```

```{r}
cases_national <- read_csv("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv")
```

```{r}
cases_national <- cases_national %>%
  filter(`Country/Region` %in% c("Germany", "France", "Italy", "Switzerland")) %>%
  filter(is.na(`Province/State`)) %>%
  select(-`Province/State`, -Lat, -Long) %>%
  melt(id.vars=c("Country/Region")) %>%
  rename(country = `Country/Region`, date = variable, cases = value) %>%
  mutate(date = as.Date(as.character(date), format = "%m/%d/%y"))
cases_national$region <- "National"
```

```{r}
days <- seq(from=as.Date('2020-01-01'), to=as.Date("2020-07-28"),by='days')
for (i in seq_along(days)) {
  for (x in unique(cases_national$country)) {
    if (length(cases_national[cases_national$country == x & cases_national$date == days[i],]$country) < 1) {
      cases_national <- rbind(cases_national, data.frame(date = days[i], country = x, cases = 0, region = "National"))
    }
  }
}
```

```{r}
cases_national <- cases_national %>%
  arrange(date, country)
```

```{r}
cases_combined <- rbind(cases_combined, cases_national) %>%
  arrange(date, country, region)
```

```{r}
cases_combined <- cases_combined %>%
  filter(date <= "2020-07-22")
```

```{r}
merged_total <- rbind(merged_national, merged_regional) %>%
  arrange(date, country, region)
```

```{r}
merged_total %>%
  filter(region != "Principality of Liechtenstein") %>%
  write_csv("C:/Users/Anelia/Desktop/projects/coronanet/WEP/WEP_analysis/data/merged_v7.csv")
```


```{r}
write_csv(merged_total, "C:/Users/Anelia/Desktop/projects/coronanet/WEP/WEP_analysis/data/merged_final.csv")
```

```{r}
merged_national
```


```{r}
merged_total$cases_national <- sapply(1:nrow(merged_total), function (i) { 
  res <- merged_national %>%
    filter(region == "National") %>%
    filter(date == merged_total$date[i]) %>%
    filter(country == merged_total$country[i])
  res$cases[1]
    })
```

```{r}
col_id <- grep("^cases_national$", names(merged_total))
merged_total <- merged_total[, c(col_id, (1:ncol(merged_total))[-col_id])]
col_id2 <- grep("^cases$", names(merged_total))
merged_total <- merged_total[, c(col_id2, (1:ncol(merged_total))[-col_id2])]
col_id3 <- grep("^region$", names(merged_total))
merged_total <- merged_total[, c(col_id3, (1:ncol(merged_total))[-col_id3])]
col_id4 <- grep("^date$", names(merged_total))
merged_total <- merged_total[, c(col_id4, (1:ncol(merged_total))[-col_id4])]
```

```{r}
merged_total <- read_csv("C:/Users/Anelia/Desktop/projects/coronanet/WEP/WEP_analysis/data/merged_v8.csv")
```


```{r}
merged_total$code <- sapply(1:nrow(merged_total), function (i) { if (!is.na(merged_total$code[[i]])) {merged_total$code[[i]]} else {
  res <- swiss_dict %>%
    filter(region == merged_total$region[i])
  res$code[1]
}})
```

```{r}
codes <- read_csv("C:/Users/Anelia/Desktop/projects/coronanet/WEP/WEP_analysis/data/codes.csv")
```


```{r}
merged_total$code <- sapply(1:nrow(merged_total), function (i) { if (!is.na(merged_total$code[[i]])) {merged_total$code[[i]]} else {
  res <- codes %>%
    filter(country == merged_total$country[i])
  res$code[1]
}})
```



```{r}
merged_total <- merged_total %>%
  filter(region != "Principality of Liechtenstein")
```

```{r}
merged_total$code <- gsub("CH04", "CH040", merged_total$code)
merged_total$code <- gsub("CH07", "CH070", merged_total$code)
```

```{r}
merged_total %>%
  group_by(code, region) %>%
  tally()
```



```{r}
swiss_dict <- geodict %>%
  filter(grepl("^CH[0-9][0-9][0-9]$", code))
swiss_dict$region <- gsub("Genève", "Geneva", swiss_dict$region)
swiss_dict$region <- gsub("Neuchâtel", "Neuchatel", swiss_dict$region)
swiss_dict$region <- gsub("Basel-Stadt", "Basel-City", swiss_dict$region)
swiss_dict$region <- gsub("Freiburg", "Fribourg", swiss_dict$region)
swiss_dict$region <- gsub("Zürich", "Zurich", swiss_dict$region)
swiss_dict$region <- gsub("St. Gallen", "Saint Gallen", swiss_dict$region)
swiss_dict$region <- gsub("Graubünden", "Grisons", swiss_dict$region)
swiss_dict$region <- gsub("Luzern", "Lucerne", swiss_dict$region)
```

```{r}
nyt_france <- read_csv("C:/Users/Anelia/Desktop/projects/coronanet/WEP/WEP_analysis/data/NYT/nyt_france_clean.csv")
```
```{r}
nyt_france %>%
  group_by(display_name) %>%
  tally()
```


```{r}
part <- nyt_france %>%
  filter(display_name == "Provence-Alpes-Côte d'Azur")
part$date <- as.Date('2020-04-13')
days <- seq(from=as.Date('2020-04-13'), to=as.Date("2020-07-19"),by='days')
for (i in seq_along(days)) {
  part$date[i] <- days[i]
}
```

```{r}
merged %>%
  select(date, region, cases, cases_national, country) %>%
  unique()
```

```{r}
merged_national <- read_csv("data/merged_national.csv")
merged_regional <- read_csv("data/merged_regional.csv")
```

